# Nome: Raylander Marques Melo
# Matrícula: 586108

In [ ]:
!pip install pandas

Collecting pandas
  Using cached pandas-2.2.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (89 kB)
Collecting numpy>=1.26.0 (from pandas)
  Using cached numpy-2.2.5-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (62 kB)
Collecting python-dateutil>=2.8.2 (from pandas)
  Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting pytz>=2020.1 (from pandas)
  Using cached pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Using cached tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting six>=1.5 (from python-dateutil>=2.8.2->pandas)
  Using cached six-1.17.0-py2.py3-none-any.whl.metadata (1.7 kB)
Using cached pandas-2.2.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.7 MB)
Using cached numpy-2.2.5-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.1 MB)
Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
Using cached pytz-2025.2-py2.py3-none-any.whl (509 kB)
Using cached six-1.17.0-py2.py3-none-any.whl (11 kB)
Using cached tzdata-2025.2-py2.py3-none-any.whl (347 kB)
Installing collected packages: pytz, tzdata, six, numpy, python-dateutil, pandas
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6/6 [pandas]━━━━ 5/6 [pandas]python-dateutil]
Successfully installed numpy-2.2.5 pandas-2.2.3 python-dateutil-2.9.0.post0 pytz-2025.2 six-1.17.0 tzdata-2025.2

In [3]:
import pandas as pd

# Crie um arquivo Jupyter Notebook e realize as seguintes operações:

## a) Ler o dataset fakeTelegram.BR_2022.csv, o qual está disponível no link a seguir: https://drive.google.com/file/d/1c_hLzk85pYw-huHSnFYZM_gn-dUsYRDm/view?usp=drive_link

In [4]:
# Abre do aquivo CSV e printa alguns elementos
df = pd.read_csv("/home/raylander/Desktop/Introdução a Ciência de Dados/fakeTelegram.BR_2022_tratado.csv")
df

,date_message,id_member_anonymous,id_group_anonymous,media,media_type,media_url,has_media,has_media_url,trava_zap,text_content_anonymous,...,id_message,message_type,messenger,media_name,media_md5,caracteres,words,viral,sharings,sentiment
0,2022-10-05 06:25:04,1078cc958f0febe28f4d03207660715f,12283e08a2eb5789201e105b34489ee7,NaN,NaN,NaN,False,False,False,Então é Fato Renato o áudio que eu ouvi no wha...,...,16385,Texto,telegram,NaN,NaN,110,20,0,1.0,0
1,2022-10-05 06:25:08,NaN,12283e08a2eb5789201e105b34489ee7,NaN,NaN,NaN,False,False,False,"Saiu no YouTube do presidente a 8 horas atrás,...",...,16386,Texto,telegram,NaN,NaN,141,23,0,1.0,1
2,2022-10-05 06:26:28,92a2d8fd7144074f659d1d29dc3751da,9f2d7394334eb224c061c9740b5748fc,NaN,NaN,NaN,False,False,False,"É isso, nossa parte já foi quase toda feita. N...",...,16366,Texto,telegram,NaN,NaN,350,59,0,1.0,-1
3,2022-10-05 06:27:28,d60aa38f62b4977426b70944af4aff72,c8f2de56550ed0bf85249608b7ead93d,94dca4cda503100ebfda7ce2bcc060eb.jpg,image/jpg,NaN,True,False,False,GENTE ACHEI ELES EM UMA SEITA MAÇONÁRICA,...,19281,Imagem,telegram,NaN,94dca4cda503100ebfda7ce2bcc060eb,40,7,0,1.0,0
4,2022-10-05 06:27:44,cd6979b0b5265f08468fa1689b6300ce,e56ec342fc599ebb4ed89655eb6f03aa,5ad5c8bbe9da93a37fecf3e5aa5b0637.jpg,image/jpg,NaN,True,False,False,NaN,...,507185,Imagem,telegram,NaN,5ad5c8bbe9da93a37fecf3e5aa5b0637,0,0,1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
557581,2022-11-11 12:06:15,333e9869f23dbd4682d1be382d9c1e59,e56ec342fc599ebb4ed89655eb6f03aa,25e43b6a58b848c43ad5b5f9e979822a.jpg,url,https://terrabrasilnoticias.com/2022/11/bndes-...,True,True,False,"BNDES tem lucro de R$ 9,6 bilhões no terceiro ...",...,575796,Url,telegram,NaN,25e43b6a58b848c43ad5b5f9e979822a,152,12,1,2.0,1
557582,2022-11-11 12:09:08,NaN,5b10d7739171149be6d9961e3350c071,657949d03e4088f6b332e2686ccd3221.jpg,url,https://youtu.be/8g1Vz9_0xVk,True,True,False,https://youtu.be/8g1Vz9_0xVk,...,1286443,Url,telegram,NaN,657949d03e4088f6b332e2686ccd3221,28,1,1,2.0,0
557583,2022-11-11 12:09:47,NaN,1590a03f43b5ba4b6147a1c5e1dd357b,a21848a61045380a6483866daed0ca0e.jpg,image/jpg,https://t.me/vemprasruas,True,True,False,"Empresários, demitam os petistas primeiro.\n\n...",...,13294,Imagem,telegram,NaN,a21848a61045380a6483866daed0ca0e,68,6,1,4.0,0
557584,2022-11-11 12:09:46,NaN,5b10d7739171149be6d9961e3350c071,a21848a61045380a6483866daed0ca0e.jpg,image/jpg,https://t.me/vemprasruas,True,True,False,"Empresários, demitam os petistas primeiro.\n\n...",...,1286444,Imagem,telegram,NaN,a21848a61045380a6483866daed0ca0e,68,6,1,4.0,0
557585,2022-11-11 12:09:48,NaN,b11f2df64ac19aad47a50accf32052d6,a21848a61045380a6483866daed0ca0e.jpg,image/jpg,https://t.me/vemprasruas,True,True,False,"Empresários, demitam os petistas primeiro.\n\n...",...,192127,Imagem,telegram,NaN,a21848a61045380a6483866daed0ca0e,68,6,1,4.0,0

## b)  Remova os trava-zaps.

In [5]:
# Soma a quantidade de elementos com True na coluna 'trava_zap' já existente no dataset
print(df['trava_zap'].sum())

16

In [6]:
# Retira as linhas que possuem trava-zap
df = df[df['trava_zap'] == False]
# Printa o dataset resultante
df

,date_message,id_member_anonymous,id_group_anonymous,media,media_type,media_url,has_media,has_media_url,trava_zap,text_content_anonymous,...,id_message,message_type,messenger,media_name,media_md5,caracteres,words,viral,sharings,sentiment
0,2022-10-05 06:25:04,1078cc958f0febe28f4d03207660715f,12283e08a2eb5789201e105b34489ee7,NaN,NaN,NaN,False,False,False,Então é Fato Renato o áudio que eu ouvi no wha...,...,16385,Texto,telegram,NaN,NaN,110,20,0,1.0,0
1,2022-10-05 06:25:08,NaN,12283e08a2eb5789201e105b34489ee7,NaN,NaN,NaN,False,False,False,"Saiu no YouTube do presidente a 8 horas atrás,...",...,16386,Texto,telegram,NaN,NaN,141,23,0,1.0,1
2,2022-10-05 06:26:28,92a2d8fd7144074f659d1d29dc3751da,9f2d7394334eb224c061c9740b5748fc,NaN,NaN,NaN,False,False,False,"É isso, nossa parte já foi quase toda feita. N...",...,16366,Texto,telegram,NaN,NaN,350,59,0,1.0,-1
3,2022-10-05 06:27:28,d60aa38f62b4977426b70944af4aff72,c8f2de56550ed0bf85249608b7ead93d,94dca4cda503100ebfda7ce2bcc060eb.jpg,image/jpg,NaN,True,False,False,GENTE ACHEI ELES EM UMA SEITA MAÇONÁRICA,...,19281,Imagem,telegram,NaN,94dca4cda503100ebfda7ce2bcc060eb,40,7,0,1.0,0
4,2022-10-05 06:27:44,cd6979b0b5265f08468fa1689b6300ce,e56ec342fc599ebb4ed89655eb6f03aa,5ad5c8bbe9da93a37fecf3e5aa5b0637.jpg,image/jpg,NaN,True,False,False,NaN,...,507185,Imagem,telegram,NaN,5ad5c8bbe9da93a37fecf3e5aa5b0637,0,0,1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
557581,2022-11-11 12:06:15,333e9869f23dbd4682d1be382d9c1e59,e56ec342fc599ebb4ed89655eb6f03aa,25e43b6a58b848c43ad5b5f9e979822a.jpg,url,https://terrabrasilnoticias.com/2022/11/bndes-...,True,True,False,"BNDES tem lucro de R$ 9,6 bilhões no terceiro ...",...,575796,Url,telegram,NaN,25e43b6a58b848c43ad5b5f9e979822a,152,12,1,2.0,1
557582,2022-11-11 12:09:08,NaN,5b10d7739171149be6d9961e3350c071,657949d03e4088f6b332e2686ccd3221.jpg,url,https://youtu.be/8g1Vz9_0xVk,True,True,False,https://youtu.be/8g1Vz9_0xVk,...,1286443,Url,telegram,NaN,657949d03e4088f6b332e2686ccd3221,28,1,1,2.0,0
557583,2022-11-11 12:09:47,NaN,1590a03f43b5ba4b6147a1c5e1dd357b,a21848a61045380a6483866daed0ca0e.jpg,image/jpg,https://t.me/vemprasruas,True,True,False,"Empresários, demitam os petistas primeiro.\n\n...",...,13294,Imagem,telegram,NaN,a21848a61045380a6483866daed0ca0e,68,6,1,4.0,0
557584,2022-11-11 12:09:46,NaN,5b10d7739171149be6d9961e3350c071,a21848a61045380a6483866daed0ca0e.jpg,image/jpg,https://t.me/vemprasruas,True,True,False,"Empresários, demitam os petistas primeiro.\n\n...",...,1286444,Imagem,telegram,NaN,a21848a61045380a6483866daed0ca0e,68,6,1,4.0,0
557585,2022-11-11 12:09:48,NaN,b11f2df64ac19aad47a50accf32052d6,a21848a61045380a6483866daed0ca0e.jpg,image/jpg,https://t.me/vemprasruas,True,True,False,"Empresários, demitam os petistas primeiro.\n\n...",...,192127,Imagem,telegram,NaN,a21848a61045380a6483866daed0ca0e,68,6,1,4.0,0

## c)  Remover as linhas repetidas (duplicadas).

In [7]:
df

,date_message,id_member_anonymous,id_group_anonymous,media,media_type,media_url,has_media,has_media_url,trava_zap,text_content_anonymous,...,id_message,message_type,messenger,media_name,media_md5,caracteres,words,viral,sharings,sentiment
0,2022-10-05 06:25:04,1078cc958f0febe28f4d03207660715f,12283e08a2eb5789201e105b34489ee7,NaN,NaN,NaN,False,False,False,Então é Fato Renato o áudio que eu ouvi no wha...,...,16385,Texto,telegram,NaN,NaN,110,20,0,1.0,0
1,2022-10-05 06:25:08,NaN,12283e08a2eb5789201e105b34489ee7,NaN,NaN,NaN,False,False,False,"Saiu no YouTube do presidente a 8 horas atrás,...",...,16386,Texto,telegram,NaN,NaN,141,23,0,1.0,1
2,2022-10-05 06:26:28,92a2d8fd7144074f659d1d29dc3751da,9f2d7394334eb224c061c9740b5748fc,NaN,NaN,NaN,False,False,False,"É isso, nossa parte já foi quase toda feita. N...",...,16366,Texto,telegram,NaN,NaN,350,59,0,1.0,-1
3,2022-10-05 06:27:28,d60aa38f62b4977426b70944af4aff72,c8f2de56550ed0bf85249608b7ead93d,94dca4cda503100ebfda7ce2bcc060eb.jpg,image/jpg,NaN,True,False,False,GENTE ACHEI ELES EM UMA SEITA MAÇONÁRICA,...,19281,Imagem,telegram,NaN,94dca4cda503100ebfda7ce2bcc060eb,40,7,0,1.0,0
4,2022-10-05 06:27:44,cd6979b0b5265f08468fa1689b6300ce,e56ec342fc599ebb4ed89655eb6f03aa,5ad5c8bbe9da93a37fecf3e5aa5b0637.jpg,image/jpg,NaN,True,False,False,NaN,...,507185,Imagem,telegram,NaN,5ad5c8bbe9da93a37fecf3e5aa5b0637,0,0,1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
557581,2022-11-11 12:06:15,333e9869f23dbd4682d1be382d9c1e59,e56ec342fc599ebb4ed89655eb6f03aa,25e43b6a58b848c43ad5b5f9e979822a.jpg,url,https://terrabrasilnoticias.com/2022/11/bndes-...,True,True,False,"BNDES tem lucro de R$ 9,6 bilhões no terceiro ...",...,575796,Url,telegram,NaN,25e43b6a58b848c43ad5b5f9e979822a,152,12,1,2.0,1
557582,2022-11-11 12:09:08,NaN,5b10d7739171149be6d9961e3350c071,657949d03e4088f6b332e2686ccd3221.jpg,url,https://youtu.be/8g1Vz9_0xVk,True,True,False,https://youtu.be/8g1Vz9_0xVk,...,1286443,Url,telegram,NaN,657949d03e4088f6b332e2686ccd3221,28,1,1,2.0,0
557583,2022-11-11 12:09:47,NaN,1590a03f43b5ba4b6147a1c5e1dd357b,a21848a61045380a6483866daed0ca0e.jpg,image/jpg,https://t.me/vemprasruas,True,True,False,"Empresários, demitam os petistas primeiro.\n\n...",...,13294,Imagem,telegram,NaN,a21848a61045380a6483866daed0ca0e,68,6,1,4.0,0
557584,2022-11-11 12:09:46,NaN,5b10d7739171149be6d9961e3350c071,a21848a61045380a6483866daed0ca0e.jpg,image/jpg,https://t.me/vemprasruas,True,True,False,"Empresários, demitam os petistas primeiro.\n\n...",...,1286444,Imagem,telegram,NaN,a21848a61045380a6483866daed0ca0e,68,6,1,4.0,0
557585,2022-11-11 12:09:48,NaN,b11f2df64ac19aad47a50accf32052d6,a21848a61045380a6483866daed0ca0e.jpg,image/jpg,https://t.me/vemprasruas,True,True,False,"Empresários, demitam os petistas primeiro.\n\n...",...,192127,Imagem,telegram,NaN,a21848a61045380a6483866daed0ca0e,68,6,1,4.0,0

In [8]:
# Remover linhas duplicadas com base em todas as colunas
df = df.drop_duplicates()
df

,date_message,id_member_anonymous,id_group_anonymous,media,media_type,media_url,has_media,has_media_url,trava_zap,text_content_anonymous,...,id_message,message_type,messenger,media_name,media_md5,caracteres,words,viral,sharings,sentiment
0,2022-10-05 06:25:04,1078cc958f0febe28f4d03207660715f,12283e08a2eb5789201e105b34489ee7,NaN,NaN,NaN,False,False,False,Então é Fato Renato o áudio que eu ouvi no wha...,...,16385,Texto,telegram,NaN,NaN,110,20,0,1.0,0
1,2022-10-05 06:25:08,NaN,12283e08a2eb5789201e105b34489ee7,NaN,NaN,NaN,False,False,False,"Saiu no YouTube do presidente a 8 horas atrás,...",...,16386,Texto,telegram,NaN,NaN,141,23,0,1.0,1
2,2022-10-05 06:26:28,92a2d8fd7144074f659d1d29dc3751da,9f2d7394334eb224c061c9740b5748fc,NaN,NaN,NaN,False,False,False,"É isso, nossa parte já foi quase toda feita. N...",...,16366,Texto,telegram,NaN,NaN,350,59,0,1.0,-1
3,2022-10-05 06:27:28,d60aa38f62b4977426b70944af4aff72,c8f2de56550ed0bf85249608b7ead93d,94dca4cda503100ebfda7ce2bcc060eb.jpg,image/jpg,NaN,True,False,False,GENTE ACHEI ELES EM UMA SEITA MAÇONÁRICA,...,19281,Imagem,telegram,NaN,94dca4cda503100ebfda7ce2bcc060eb,40,7,0,1.0,0
4,2022-10-05 06:27:44,cd6979b0b5265f08468fa1689b6300ce,e56ec342fc599ebb4ed89655eb6f03aa,5ad5c8bbe9da93a37fecf3e5aa5b0637.jpg,image/jpg,NaN,True,False,False,NaN,...,507185,Imagem,telegram,NaN,5ad5c8bbe9da93a37fecf3e5aa5b0637,0,0,1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
557581,2022-11-11 12:06:15,333e9869f23dbd4682d1be382d9c1e59,e56ec342fc599ebb4ed89655eb6f03aa,25e43b6a58b848c43ad5b5f9e979822a.jpg,url,https://terrabrasilnoticias.com/2022/11/bndes-...,True,True,False,"BNDES tem lucro de R$ 9,6 bilhões no terceiro ...",...,575796,Url,telegram,NaN,25e43b6a58b848c43ad5b5f9e979822a,152,12,1,2.0,1
557582,2022-11-11 12:09:08,NaN,5b10d7739171149be6d9961e3350c071,657949d03e4088f6b332e2686ccd3221.jpg,url,https://youtu.be/8g1Vz9_0xVk,True,True,False,https://youtu.be/8g1Vz9_0xVk,...,1286443,Url,telegram,NaN,657949d03e4088f6b332e2686ccd3221,28,1,1,2.0,0
557583,2022-11-11 12:09:47,NaN,1590a03f43b5ba4b6147a1c5e1dd357b,a21848a61045380a6483866daed0ca0e.jpg,image/jpg,https://t.me/vemprasruas,True,True,False,"Empresários, demitam os petistas primeiro.\n\n...",...,13294,Imagem,telegram,NaN,a21848a61045380a6483866daed0ca0e,68,6,1,4.0,0
557584,2022-11-11 12:09:46,NaN,5b10d7739171149be6d9961e3350c071,a21848a61045380a6483866daed0ca0e.jpg,image/jpg,https://t.me/vemprasruas,True,True,False,"Empresários, demitam os petistas primeiro.\n\n...",...,1286444,Imagem,telegram,NaN,a21848a61045380a6483866daed0ca0e,68,6,1,4.0,0
557585,2022-11-11 12:09:48,NaN,b11f2df64ac19aad47a50accf32052d6,a21848a61045380a6483866daed0ca0e.jpg,image/jpg,https://t.me/vemprasruas,True,True,False,"Empresários, demitam os petistas primeiro.\n\n...",...,192127,Imagem,telegram,NaN,a21848a61045380a6483866daed0ca0e,68,6,1,4.0,0

## d)  Remover textos com menos de 5 palavras.

In [9]:
# Função para contar o número de palavras
def count_words(text):
    if isinstance(text, str):  # Verifica se o valor é uma string
        return len(text.split())
    return 0  # Caso não seja string, retorna 0 palavras

# Adiciona a coluna 'word_count' ao DataFrame
df['word_count'] = df['text_content_anonymous'].apply(count_words)

# Filtra os textos com mais de 5 palavras
df = df[df['word_count'] >= 5]
df

,date_message,id_member_anonymous,id_group_anonymous,media,media_type,media_url,has_media,has_media_url,trava_zap,text_content_anonymous,...,message_type,messenger,media_name,media_md5,caracteres,words,viral,sharings,sentiment,word_count
0,2022-10-05 06:25:04,1078cc958f0febe28f4d03207660715f,12283e08a2eb5789201e105b34489ee7,NaN,NaN,NaN,False,False,False,Então é Fato Renato o áudio que eu ouvi no wha...,...,Texto,telegram,NaN,NaN,110,20,0,1.0,0,20
1,2022-10-05 06:25:08,NaN,12283e08a2eb5789201e105b34489ee7,NaN,NaN,NaN,False,False,False,"Saiu no YouTube do presidente a 8 horas atrás,...",...,Texto,telegram,NaN,NaN,141,23,0,1.0,1,23
2,2022-10-05 06:26:28,92a2d8fd7144074f659d1d29dc3751da,9f2d7394334eb224c061c9740b5748fc,NaN,NaN,NaN,False,False,False,"É isso, nossa parte já foi quase toda feita. N...",...,Texto,telegram,NaN,NaN,350,59,0,1.0,-1,59
3,2022-10-05 06:27:28,d60aa38f62b4977426b70944af4aff72,c8f2de56550ed0bf85249608b7ead93d,94dca4cda503100ebfda7ce2bcc060eb.jpg,image/jpg,NaN,True,False,False,GENTE ACHEI ELES EM UMA SEITA MAÇONÁRICA,...,Imagem,telegram,NaN,94dca4cda503100ebfda7ce2bcc060eb,40,7,0,1.0,0,7
5,2022-10-05 06:28:30,NaN,b52442a5fbc459ae590dca0d215e32f9,NaN,NaN,NaN,False,False,False,Kķkkkkk to rindo até agora....Quem disse q ia ...,...,Texto,telegram,NaN,NaN,133,25,0,1.0,1,25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
557580,2022-11-11 12:05:41,3e49fd40fd973ee1b8f1a6d58feb4a54,4c6519d965020abc048521dfa837b9bb,9dd3b338a07226a04f97df82fbbcb36b.jpg,image/jpg,https://t.me/Manager_Marcus_Chat_Up_Now,True,True,False,NOVOS MEMBROS SEMPRE CLICAM NO LINK DO ADMINIS...,...,Imagem,telegram,NaN,9dd3b338a07226a04f97df82fbbcb36b,254,28,1,12.0,0,28
557581,2022-11-11 12:06:15,333e9869f23dbd4682d1be382d9c1e59,e56ec342fc599ebb4ed89655eb6f03aa,25e43b6a58b848c43ad5b5f9e979822a.jpg,url,https://terrabrasilnoticias.com/2022/11/bndes-...,True,True,False,"BNDES tem lucro de R$ 9,6 bilhões no terceiro ...",...,Url,telegram,NaN,25e43b6a58b848c43ad5b5f9e979822a,152,12,1,2.0,1,12
557583,2022-11-11 12:09:47,NaN,1590a03f43b5ba4b6147a1c5e1dd357b,a21848a61045380a6483866daed0ca0e.jpg,image/jpg,https://t.me/vemprasruas,True,True,False,"Empresários, demitam os petistas primeiro.\n\n...",...,Imagem,telegram,NaN,a21848a61045380a6483866daed0ca0e,68,6,1,4.0,0,6
557584,2022-11-11 12:09:46,NaN,5b10d7739171149be6d9961e3350c071,a21848a61045380a6483866daed0ca0e.jpg,image/jpg,https://t.me/vemprasruas,True,True,False,"Empresários, demitam os petistas primeiro.\n\n...",...,Imagem,telegram,NaN,a21848a61045380a6483866daed0ca0e,68,6,1,4.0,0,6
557585,2022-11-11 12:09:48,NaN,b11f2df64ac19aad47a50accf32052d6,a21848a61045380a6483866daed0ca0e.jpg,image/jpg,https://t.me/vemprasruas,True,True,False,"Empresários, demitam os petistas primeiro.\n\n...",...,Imagem,telegram,NaN,a21848a61045380a6483866daed0ca0e,68,6,1,4.0,0,6

# Utilizando o PostgreSQL e o Metabase faça as seguintes operações:

In [10]:
!pip install sqlalchemy psycopg2

Collecting sqlalchemy
  Using cached sqlalchemy-2.0.41-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.6 kB)
Collecting psycopg2
  Using cached psycopg2-2.9.10.tar.gz (385 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting greenlet>=1 (from sqlalchemy)
  Downloading greenlet-3.2.2-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (4.1 kB)
Collecting typing-extensions>=4.6.0 (from sqlalchemy)
  Using cached typing_extensions-4.13.2-py3-none-any.whl.metadata (3.0 kB)
Downloading sqlalchemy-2.0.41-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 5.8 MB/s eta 0:00:004 MB/s eta 0:00:01
Downloading greenlet-3.2.2-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (603 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 603.9/603.9 kB 2.1 MB/s eta 0:00:00
Using cached typing_extensions-4.13.2-py3-none-any.whl (45 kB)
Building wheels for collected packages: psycopg2
  Building wheel for psycopg2 (pyproject.toml) ... done
  Created wheel for psycopg2: filename=psycopg2-2.9.10-cp312-cp312-linux_x86_64.whl size=529597 sha256=d1d7ebfe9acae34dfd419de2bb1435f0ea9ef1f07e26532e0a89f29de73171fa
  Stored in directory: /home/raylander/.cache/pip/wheels/ac/bb/ce/afa589c50b6004d3a06fc691e71bd09c9bd5f01e5921e5329b
Successfully built psycopg2
Installing collected packages: typing-extensions, psycopg2, greenlet, sqlalchemy
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4/4 [sqlalchemy] 3/4 [sqlalchemy]
Successfully installed greenlet-3.2.2 psycopg2-2.9.10 sqlalchemy-2.0.41 typing-extensions-4.13.2

In [12]:
from sqlalchemy import create_engine

usuario = 'raylander'
senha = 'senha'
host = 'localhost'
porta = '5433'
banco = 'meu_banco'

engine = create_engine(f'postgresql+psycopg2://{usuario}:{senha}@{host}:{porta}/{banco}')

df.to_sql('fake_telegram', engine, if_exists='replace', index=False)

286

## a)  Crie dashboards para apresentar:

### 1.  As quantidades de grupos, usuários e mensagens;

![Texto alternativo](../Lista%204/graficos/item_1.png)

### 2.  A quantidade de mensagens que possuem apenas texto X mídia;

![Texto alternativo](../Lista%204/graficos/item_2_0.png)

![Texto alternativo](../Lista%204/graficos/item_2_1.png)

### 3.  Quantidade de mensagens por tipo de mídia (jpg, mp4 etc);

![Texto alternativo](../Lista%204/graficos/item_3.png)

### 4.  A  relação  entre  a  quantidade  de  mensagens  e  a  quantidade  de  palavras presente nas mensagens;

![Texto alternativo](../Lista%204/graficos/item_4.png)

### 5.  Quantidade de mensagens por estado;

### 6.  Quantidade de usuários por estado;

### 7.  Relação quantidade de usuários por quantidade de mensagens por estado;

### 8.  Quantidade de mensagens por país;

### 9.  Quantidade de mensagens Brasil X Países Estrangeiros;

### 10. As 30 URLs que mais se repetem (mais compartilhadas);

![Texto alternativo](../Lista%204/graficos/item_10.png)

### 11. Os 30 domínios que mais se repetem (mais compartilhados);

In [ ]:
from urllib.parse import urlparse

# Exemplo: df é o seu DataFrame com a coluna 'media_url'
def extrair_dominio(url):
    if pd.isnull(url):
        return None
    try:
        return urlparse(url).netloc
    except:
        return None

# Criar nova coluna com os domínios

df['media_domain'] = df['media_url'].apply(extrair_dominio)

/tmp/ipykernel_4981/2443469279.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['media_domain'] = df['media_url'].apply(extrair_dominio)

In [13]:
from sqlalchemy import create_engine

usuario = 'raylander'
senha = 'senha'
host = 'localhost'
porta = '5433'
banco = 'meu_banco'

engine = create_engine(f'postgresql+psycopg2://{usuario}:{senha}@{host}:{porta}/{banco}')

df.to_sql('fake_telegram', engine, if_exists='replace', index=False)

286

![Texto alternativo](../Lista%204/graficos/item_11.png)

### 12. Os 30 usuários mais ativos;

![Texto alternativo](../Lista%204/graficos/item_12.png)

### 13. Relação  entre  quantidade  de  mensagens  contendo  somente  texto  e mensagens com tendo mídia dos usuários mais ativos:

![Texto alternativo](../Lista%204/graficos/item_13.png)

### 14. Os 30 usuários que mais compartilharam texto;

![Texto alternativo](../Lista%204/graficos/item_14.png)

### 15. Os 30 usuários que mais compartilharam mídias;

![Texto alternativo](../Lista%204/graficos/item_15.png)

### 16. As 30 mensagens mais compartilhadas;

![Texto alternativo](../Lista%204/graficos/item_16.png)

### 17. As 30 mensagens mais compartilhadas em grupos diferentes;

![Texto alternativo](../Lista%204/graficos/item_17.png)

### 18. Mensagens  idênticas  compartilhadas  pelo  mesmo  usuário  (e  suas quantidades);

![Texto alternativo](../Lista%204/graficos/item_18.png)

### 19. Mensagens  idênticas  compartilhadas  pelo  mesmo  usuário  em  grupos distintos (e suas quantidades);

![Texto alternativo](../Lista%204/graficos/item_19.png)

### 20. Os 30 unigramas, bigramas e trigramas mais compartilhados (após a remoção de stop words);

![Texto alternativo](../Lista%204/graficos/item_20_0.png)

### 21. As 30 mensagens mais positivas (distintas);

![Texto alternativo](../Lista%204/graficos/item_21.png)

### 22. As 30 mensagens mais negativas (distintas);

![Texto alternativo](../Lista%204/graficos/item_22.png)

### 23. O usuário mais otimista;

![Texto alternativo](../Lista%204/graficos/item_23.png)

### 24. O usuário mais pessimista;

![Texto alternativo](../Lista%204/graficos/item_24.png)

### 25. As 30 maiores mensagens;

![Texto alternativo](../Lista%204/graficos/item_25.png)

### 26. As 30 menores mensagens;

![Texto alternativo](../Lista%204/graficos/item_26.png)

### 27. O dia em que foi publicado a maior quantidade de mensagens;

![Texto alternativo](../Lista%204/graficos/item_27.png)

### 28. As mensagens que possuem as palavras “FACÇÃO” e “CRIMINOSA”;

![Texto alternativo](../Lista%204/graficos/item_28.png)

### 29. Quantidade de mensagens por dia e hora;

![Texto alternativo](../Lista%204/graficos/item_29.png)

### 30. Quantidade de mensagens por hora;

![Texto alternativo](../Lista%204/graficos/item_30.png)

### 31. A nuvem de palavras referente às mensagens de texto (após a remoção de stop words);

![Texto alternativo](../Lista%204/graficos/item_31.png)

![Texto alternativo](../Lista%204/graficos/item_31_1.png)

### 32. A  rede  interativa  das  palavras  referente  às  mensagens  de  texto  (após  a remoção de stop words);

![Texto alternativo](../Lista%204/graficos/item)

### 33. Proporção de mensagens com e sem URL;

![Texto alternativo](../Lista%204/graficos/item_33.png)

### 34. Proporção de desinformação;

![Texto alternativo](../Lista%204/graficos/item_34.png)

### 35. Proporção de mensagens contendo mídia e desinformação;

![Texto alternativo](../Lista%204/graficos/item_35.png)

![Texto alternativo](../Lista%204/graficos/item_35_1.png)

### 36. Distribuição de mensagens por score de desinformação;

![Texto alternativo](../Lista%204/graficos/item_34.png)

### 37. Proporção de sentimentos;

![Texto alternativo](../Lista%204/graficos/item_37.png)

### 38. Distribuição de mensagens por score de sentimentos;

![Texto alternativo](../Lista%204/graficos/item_37.png)

### 39. Proporção entre mensagens virais e não virais;

![Texto alternativo](../Lista%204/graficos/item_39,.png)

### 40. Algo que você julga importante e que ainda não foi solicitado;

![Texto alternativo](../Lista%204/graficos/item_40.png)